version: "3"
services:

  php-fpm:
    container_name: "php-fpm"
    restart: always
    image: php:7.4.33-fpm-alpine
    environment:
      TZ: "Asia/Shanghai"
    # links:
    #   - "go-cqhttp"
    volumes:
      - "/www/wwwroot/website:/usr/share/nginx/html"
      - "/www/wwwroot/config/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "/www/wwwroot/config/php.ini:/usr/local/etc/php-8.2.2/php.ini"

  nginx:
    image: nginx:1.23.3
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php-fpm"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "/www/wwwroot/website:/usr/share/nginx/html"
      - "/www/wwwroot/config/default.conf:/etc/nginx/conf.d/default.conf"
